version: "3.7"
services:
  backend:
    build: ./timezoneBackend
    restart: on-failure
    ports:
      - 8080:8080
    depends_on:
      - postgres_db

  postgres_db:
    image: "postgres:11.4"
    restart: on-failure
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=1234
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
  frontend:
    build: ./timezone-frontend
    restart: on-failure
    ports:
      - 3000:3000